package com.jackie.blogasd.mapper;

import com.jackie.blogasd.model.Tpermission;
import org.springframework.stereotype.Repository;

@Repository
public interface TpermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbg.generated Mon Jul 08 09:23:15 CST 2019
     */
    int deleteByPrimaryKey(String tpId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbg.generated Mon Jul 08 09:23:15 CST 2019
     */
    int insert(Tpermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbg.generated Mon Jul 08 09:23:15 CST 2019
     */
    int insertSelective(Tpermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbg.generated Mon Jul 08 09:23:15 CST 2019
     */
    Tpermission selectByPrimaryKey(String tpId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbg.generated Mon Jul 08 09:23:15 CST 2019
     */
    int updateByPrimaryKeySelective(Tpermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbg.generated Mon Jul 08 09:23:15 CST 2019
     */
    int updateByPrimaryKey(Tpermission record);
}