package com.jackie.blogasd.mapper;

import com.jackie.blogasd.model.Trole;

public interface TroleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbg.generated Tue Jun 18 15:39:52 CST 2019
     */
    int deleteByPrimaryKey(String trId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbg.generated Tue Jun 18 15:39:52 CST 2019
     */
    int insert(Trole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbg.generated Tue Jun 18 15:39:52 CST 2019
     */
    int insertSelective(Trole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbg.generated Tue Jun 18 15:39:52 CST 2019
     */
    Trole selectByPrimaryKey(String trId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbg.generated Tue Jun 18 15:39:52 CST 2019
     */
    int updateByPrimaryKeySelective(Trole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbg.generated Tue Jun 18 15:39:52 CST 2019
     */
    int updateByPrimaryKey(Trole record);
}