package com.jackie.blogasd.mapper;

import com.jackie.blogasd.model.Tuser;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Jul 08 09:23:15 CST 2019
     */
    int deleteByPrimaryKey(String tuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Jul 08 09:23:15 CST 2019
     */
    int insert(Tuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Jul 08 09:23:15 CST 2019
     */
    int insertSelective(Tuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Jul 08 09:23:15 CST 2019
     */
    Tuser selectByPrimaryKey(String tuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Jul 08 09:23:15 CST 2019
     */
    int updateByPrimaryKeySelective(Tuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Jul 08 09:23:15 CST 2019
     */
    int updateByPrimaryKey(Tuser record);

    Tuser getUserByUsername(@Param("username")String username);
}