package com.jackie.blogasd.model;

import java.util.Date;

public class Trole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.tr_id
     *
     * @mbg.generated Tue Jun 18 15:39:52 CST 2019
     */
    private String trId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.parent_tr_id
     *
     * @mbg.generated Tue Jun 18 15:39:52 CST 2019
     */
    private String parentTrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.role_name
     *
     * @mbg.generated Tue Jun 18 15:39:52 CST 2019
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.create_time
     *
     * @mbg.generated Tue Jun 18 15:39:52 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.description
     *
     * @mbg.generated Tue Jun 18 15:39:52 CST 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.tr_id
     *
     * @return the value of t_role.tr_id
     *
     * @mbg.generated Tue Jun 18 15:39:52 CST 2019
     */
    public String getTrId() {
        return trId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.tr_id
     *
     * @param trId the value for t_role.tr_id
     *
     * @mbg.generated Tue Jun 18 15:39:52 CST 2019
     */
    public void setTrId(String trId) {
        this.trId = trId == null ? null : trId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.parent_tr_id
     *
     * @return the value of t_role.parent_tr_id
     *
     * @mbg.generated Tue Jun 18 15:39:52 CST 2019
     */
    public String getParentTrId() {
        return parentTrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.parent_tr_id
     *
     * @param parentTrId the value for t_role.parent_tr_id
     *
     * @mbg.generated Tue Jun 18 15:39:52 CST 2019
     */
    public void setParentTrId(String parentTrId) {
        this.parentTrId = parentTrId == null ? null : parentTrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.role_name
     *
     * @return the value of t_role.role_name
     *
     * @mbg.generated Tue Jun 18 15:39:52 CST 2019
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.role_name
     *
     * @param roleName the value for t_role.role_name
     *
     * @mbg.generated Tue Jun 18 15:39:52 CST 2019
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.create_time
     *
     * @return the value of t_role.create_time
     *
     * @mbg.generated Tue Jun 18 15:39:52 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.create_time
     *
     * @param createTime the value for t_role.create_time
     *
     * @mbg.generated Tue Jun 18 15:39:52 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.description
     *
     * @return the value of t_role.description
     *
     * @mbg.generated Tue Jun 18 15:39:52 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.description
     *
     * @param description the value for t_role.description
     *
     * @mbg.generated Tue Jun 18 15:39:52 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}